# Perceptron

## 파이썬으로 간단하게 구현한 퍼셉트론-1

In [1]:
import numpy as np
X=np.array([1,0,1])
X

array([1, 0, 1])

In [2]:
W=np.array([
    -0.5,
    1.0,
    1.0
])
W

array([-0.5,  1. ,  1. ])

In [3]:
y=sum(X*W)
y

0.5

## 파이썬으로 간단하게 구현한 퍼셉트론-2

In [4]:
import numpy as np
X=np.array([
            [1,0,0],
            [1,0,1],
            [1,1,0],
            [1,1,1]
])
X

array([[1, 0, 0],
       [1, 0, 1],
       [1, 1, 0],
       [1, 1, 1]])

In [5]:
W=np.array([
    -0.5,
    1.0,
    1.0
])
W

array([-0.5,  1. ,  1. ])

In [6]:
y=np.sum(X*W, axis=1)
y

array([-0.5,  0.5,  0.5,  1.5])

## SLP를 통한 AND, OR, NOT 게이트 문제

### 퍼셉트론 구현하기

In [7]:
import numpy as np
def ANDperceptron(x1, x2):
    w1, w2, theta = 0.5, 0.5, 0.7
    tmp = x1*w1 + x2*w2
    if tmp <= theta:
        return 0
    elif tmp > theta:
        return 1

inputData = np.array([[0,0],[0,1],[1,0],[1,1]])

print("+++ AND Perceptron +++")
for xs in inputData:
    print(str(xs) + " >>> " + str(ANDperceptron(xs[0], xs[1])))

+++ AND Perceptron +++
[0 0] >>> 0
[0 1] >>> 0
[1 0] >>> 0
[1 1] >>> 1


In [8]:
import numpy as np
def ANDperceptron(x1, x2):
    x = np.array([x1, x2])
    w = np.array([0.5, 0.5])
    b = -0.7
    tmp = np.sum(w*x) + b
    if tmp <= 0:
        return 0
    elif tmp > 0:
        return 1

inputData = np.array([[0,0],[0,1],[1,0],[1,1]])

print("+++ AND Perceptron +++")

for xs in inputData:
    print(str(xs) + " >>> " + str(ANDperceptron(xs[0], xs[1])))

+++ AND Perceptron +++
[0 0] >>> 0
[0 1] >>> 0
[1 0] >>> 0
[1 1] >>> 1


In [9]:
import numpy as np

#데이터 생성
rng = np.random.RandomState(123)
d = 2
N = 10
mean = 5
x1 = rng.randn(N, d) + np.array([0, 0])
x2 = rng.randn(N, d) + np.array([mean, mean])
x = np.concatenate((x1, x2), axis=0)

#단순 퍼셉트론
w = np.zeros(d)
b = 0

def y(x):
    return step(np.dot(w, x) + b)

def step(x):
    return 1 * (x > 0)

def t(i):
    if i < N:
        return 0
    else:
        return 1

while True:
    classified = True
    for i in range(N * 2):
        delta_w = (t(i) - y(x[i])) * x[i]
        delta_b = (t(i) - y(x[i]))
        w += delta_w
        b += delta_b
        classified *= all(delta_w == 0) * (delta_b == 0)
    if classified:
        break

print('w:', w)
print('b:', b)
print('\nTest:')
print(y([0, 0]))  # => 0
print(y([5, 5]))  # => 1

w: [2.14037745 1.2763927 ]
b: -9

Test:
0
1


### AND 게이트 단순 퍼셉트론 구현하기

In [10]:
import numpy as np

# AND 데이터 만들기

X = np.array([[0, 0], [1, 0], [0, 1], [1, 1]])
y = np.array([0, 0, 0, 1])

# 1단계 : 가중치 초기화

w = np.zeros(1 + X.shape[1])

# 최초 분류

input_signal = np.dot(X, w[1:]) + w[0]
def out_put(X):
    return np.where(X >= 0.0, 1, 0)
pred_y = out_put(input_signal)
print(pred_y)

# 가중치 최적화 시작

errors = []
epoch = 100
for time in range(0, epoch):
    print("{0}번째 반복 입니다".format(time))
    eta = 0.01
    idx = 0
    for xi, target in zip(X, y):
        updated_w = eta * (target - pred_y[idx])
        w[1:] += updated_w * xi
        w[0] += updated_w
        idx += 1
    input_signal = np.dot(X, w[1:]) + w[0]
    pred_y = out_put(input_signal)
    errors.append(((y - pred_y).sum()) / 100)
    print(((y - pred_y).sum()) / 100)
    if ((y - pred_y).sum()) / 100 == 0:
        break

print(pred_y)

[1 1 1 1]
0번째 반복 입니다
0.01
1번째 반복 입니다
0.01
2번째 반복 입니다
-0.02
3번째 반복 입니다
0.01
4번째 반복 입니다
0.0
[0 0 0 1]


### OR

In [11]:
import numpy as np

# OR 데이터 만들기
X = np.array([[0, 0], [1, 0], [0, 1], [1, 1]])
y = np.array([0, 1, 1, 1])

# 1단계 : 가중치 초기화
w = np.zeros(1 + X.shape[1])

# 최초 분류
input_signal = np.dot(X, w[1:]) + w[0]

def out_put(X):
    return np.where(X >= 0.0, 1, 0)

pred_y = out_put(input_signal)
print(pred_y)

# 가중치 최적화 시작
errors = []
epoch = 100
for time in range(0, epoch):
    print("{0}번째 반복 입니다".format(time))
    eta = 0.01
    idx = 0
    for xi, target in zip(X, y):
        updated_w = eta * (target - pred_y[idx])
        w[1:] += updated_w * xi
        w[0] += updated_w
        idx += 1
    input_signal = np.dot(X, w[1:]) + w[0]
    pred_y = out_put(input_signal)
    errors.append(((y - pred_y).sum()) / 100)
    print(((y - pred_y).sum()) / 100)
    if ((y - pred_y).sum()) / 100 == 0:
        break
print(pred_y)

[1 1 1 1]
0번째 반복 입니다
0.03
1번째 반복 입니다
-0.01
2번째 반복 입니다
-0.01
3번째 반복 입니다
-0.01
4번째 반복 입니다
0.0
[0 1 1 1]


### NAND 게이트 단순 퍼셉트론 화

In [12]:
import numpy as np

# NAND 데이터 만들기
X = np.array([[0, 0], [1, 0], [0, 1], [1, 1]])
y = np.array([1, 0, 0, 0])

# 1단계 : 가중치 초기화
w = np.zeros(1 + X.shape[1])

# 최초 분류
input_signal = np.dot(X, w[1:]) + w[0]

def out_put(X):
    return np.where(X >= 0.0, 1, 0)

pred_y = out_put(input_signal)
print(pred_y)

# 가중치 최적화 시작
errors = []
epoch = 100
for time in range(0, epoch):
    print("{0}번째 반복 입니다".format(time))
    eta = 0.01
    idx = 0
    for xi, target in zip(X, y):
        updated_w = eta * (target - pred_y[idx])
        w[1:] += updated_w * xi
        w[0] += updated_w
        idx += 1
    input_signal = np.dot(X, w[1:]) + w[0]
    pred_y = out_put(input_signal)
    errors.append(((y - pred_y).sum()) / 100)
    print(((y - pred_y).sum()) / 100)
    if ((y - pred_y).sum()) / 100 == 0:
        break
print(pred_y)

[1 1 1 1]
0번째 반복 입니다
0.01
1번째 반복 입니다
0.01
2번째 반복 입니다
0.01
3번째 반복 입니다
0.0
[1 0 0 0]


### Quiz- NOR  게이트 단순 퍼셉트론

In [13]:
import numpy as np

# Quiz- NOR 데이터 만들기
X = np.array([[0, 0], [1, 0], [0, 1], [1, 1]])
y = np.array([1, 1, 1, 0])

# 1단계 : 가중치 초기화
w = np.zeros(1 + X.shape[1])

# 최초 분류
input_signal = np.dot(X, w[1:]) + w[0]

def out_put(X):
    return np.where(X >= 0.0, 1, 0)

pred_y = out_put(input_signal)
print(pred_y)

# 가중치 최적화 시작
errors = []
epoch = 100
for time in range(0, epoch):
    print("{0}번째 반복 입니다".format(time))
    eta = 0.01
    idx = 0
    for xi, target in zip(X, y):
        updated_w = eta * (target - pred_y[idx])
        w[1:] += updated_w * xi
        w[0] += updated_w
        idx += 1
    input_signal = np.dot(X, w[1:]) + w[0]
    pred_y = out_put(input_signal)
    errors.append(((y - pred_y).sum()) / 100)
    print(((y - pred_y).sum()) / 100)
    if ((y - pred_y).sum()) / 100 == 0:
        break
print(pred_y)

[1 1 1 1]
0번째 반복 입니다
0.03
1번째 반복 입니다
-0.01
2번째 반복 입니다
0.0
[1 1 1 0]


### XOR 게이트 구현하기

In [14]:
def AND(x1, x2):
    x = np.array([x1, x2])
    w = np.array([0.5, 0.5])
    b = -0.7
    tmp = np.sum(w*x) + b
    if tmp <= 0:
        return 0
    elif tmp > 0:
        return 1


def OR(x1, x2):
    x = np.array([x1, x2])
    w = np.array([0.5, 0.5])
    b = -0.2
    tmp = np.sum(w*x) + b
    if tmp <= 0:
        return 0
    else:
        return 1

def NAND(x1, x2):
    x = np.array([x1, x2])
    w = np.array([-0.5, -0.5])
    b = 0.7
    tmp = np.sum(w*x) + b
    if tmp <= 0:
        return 0
    else:
        return 1

def XOR(x1, x2):
    s1 = NAND(x1, x2)
    s2 = OR(x1, x2)
    y = AND(s1, s2)
    return y

In [15]:
import numpy as np

print(XOR(0,0))
print(XOR(1,0))
print(XOR(0,1))
print(XOR(1,1))

0
1
1
0


# XOR 문제를 MLP로 풀어보기

## 파이썬 버전

In [16]:
# 1. 패키지 로드
import numpy as np

# 2. MLP 구조 구성하는 게이트 클래스 구현
def sigmoid(x):
  return 1/(1+np.exp(-x))
def numerical_derivative(f, x):
  delta_x = 1e-4
  grad = np.zeros_like(x)
  it=np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
  while not it.finished:
    idx=it.multi_index
    tmp_val=x[idx]
    x[idx]=float(tmp_val) + delta_x
    fx1 = f(x)
    x[idx]=float(tmp_val) - delta_x
    fx2 = f(x)
    grad[idx]=(fx1 - fx2) / (2*delta_x)
    x[idx]=tmp_val
    it.iternext()
  return grad


class LogicGate:
  def __init__(self, gate_name, xdata, tdata):
    self.name=gate_name
    self.__xdata=xdata.reshape(4,2)
    self.__tdata=tdata.reshape(4,1)
    self.__w=np.random.rand(2,1)
    self.__b=np.random.rand(1)
    self.__learning_rate=1e-2
  # 손실 함수
  def __loss_function(self):
    delta=1e-7
    z=np.dot(self.__xdata, self.__w) + self.__b
    y=sigmoid(z)
    return -np.sum(self.__tdata*np.log(y+delta) + (1-self.__tdata)*np.log((1-y)+delta))
  # 손실 값 계산 함수
  def error_val(self):
    return self.__loss_function()


#학습
  def train(self):
    #손실함수 계산
    f=lambda x: self.__loss_function()
    print("초기 에러 값 = ", self.error_val())
    #손실함수에 대해 경사하강 가중치, 바이어스 업데이트
    for step in range(8001):
      self.__w -= self.__learning_rate * numerical_derivative(f, self.__w)
      self.__b -= self.__learning_rate * numerical_derivative(f, self.__b)
      if(step %400==0):
        print("step = ",step, "에러 값 = ", self.error_val())
  #예측 함수
  def predict(self, input_data):
    z=np.dot(input_data, self.__w) + self.__b
    y=sigmoid(z)
    if y > 0.5:
      result = 1
    else:
      result = 0
    return y, result


# AND
xdata=np.array([[0,0],[0,1],[1,0],[1,1]])
tdata=np.array([0,0,0,1])
AND_g=LogicGate("AND_GATE", xdata, tdata)
AND_g.train()
print(AND_g.name, '\n')
test_data=np.array([[0,0],[0,1],[1,0],[1,1]])
for input_data in test_data:
  (sigmoid_val, logical_val)=AND_g.predict(input_data)
  print(input_data, "=", logical_val, "\n")



# NAND
xdata=np.array([[0,0],[0,1],[1,0],[1,1]])
tdata=np.array([1,1,1,0])
NAND_g=LogicGate("NAND_GATE", xdata, tdata)
NAND_g.train()
print(NAND_g.name, '\n')
test_data=np.array([[0,0],[0,1],[1,0],[1,1]])
for input_data in test_data:
  (sigmoid_val, logical_val)=NAND_g.predict(input_data)
  print(input_data, "=", logical_val, "\n")



# OR
xdata=np.array([[0,0],[0,1],[1,0],[1,1]])
tdata=np.array([0,1,1,1])
OR_g=LogicGate("OR_GATE", xdata, tdata)
OR_g.train()
print(OR_g.name, '\n')
test_data=np.array([[0,0],[0,1],[1,0],[1,1]])
for input_data in test_data:
  (sigmoid_val, logical_val)=OR_g.predict(input_data)
  print(input_data, "=", logical_val, "\n")



# XOR 계산하기
input_data=np.array([[0,0],[0,1],[1,0],[1,1]])
s1=[] #NAND
s2=[] #OR
new_input_data=[] #AND 입력
final_output=[] #AND 출력
for index in range(len(input_data)):
  s1=NAND_g.predict(input_data[index])
  s2=OR_g.predict(input_data[index])
  new_input_data.append(s1[-1])
  new_input_data.append(s2[-1])
  (sigmoid_val, logical_val)=AND_g.predict(np.array(new_input_data))
  final_output.append(logical_val)
  new_input_data=[] #AND 입력 초기화
for index in range(len(input_data)):
  print(input_data[index], "=", final_output[index], end='')
  print('\n')

초기 에러 값 =  4.127670390247806
step =  0 에러 값 =  4.07978526058836
step =  400 에러 값 =  1.5621020980112343
step =  800 에러 값 =  1.1555769156034355
step =  1200 에러 값 =  0.9268398356910397
step =  1600 에러 값 =  0.7765611656753602
step =  2000 에러 값 =  0.6688617148800461
step =  2400 에러 값 =  0.5873652861290213
step =  2800 에러 값 =  0.5233542153139319
step =  3200 에러 값 =  0.47168027911926336
step =  3600 에러 값 =  0.4290725157635775
step =  4000 에러 값 =  0.3933378034154106
step =  4400 에러 값 =  0.3629439114779699
step =  4800 에러 값 =  0.33678492977990254
step =  5200 에러 값 =  0.3140412439127129
step =  5600 에러 값 =  0.2940918916722082
step =  6000 에러 값 =  0.276457542357491
step =  6400 에러 값 =  0.2607621873207216
step =  6800 에러 값 =  0.24670669298371944
step =  7200 에러 값 =  0.23405011288992456
step =  7600 에러 값 =  0.2225962125932231
step =  8000 에러 값 =  0.21218357914171548
AND_GATE 

[0 0] = 0 

[0 1] = 0 

[1 0] = 0 

[1 1] = 1 

초기 에러 값 =  2.879969188781502
step =  0 에러 값 =  2.8709525860134146
step =  4

## 딥러닝 버전

In [19]:
import numpy as np

# 시그모이드 구하는 함수
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# 수치 미분 함수
def numerical_derivative(f, input_data):
    delta_x = 1e-4
    ret = np.zeros_like(input_data)
    it = np.nditer(input_data, flags=['multi_index'])
    while not it.finished:
        idx = it.multi_index
        tmp = input_data[idx]
        input_data[idx] = float(tmp) + delta_x
        fx1 = f(input_data)
        input_data[idx] = float(tmp) - delta_x
        fx2 = f(input_data)
        ret[idx] = (fx1 - fx2) / (2 * delta_x)
        input_data[idx] = tmp
        it.iternext()
    return ret

class LogicGate:
    def __init__(self, gate_name, x_data, t_data):
        self.name = gate_name
        # 입력 데이터
        self.__x_data = x_data
        self.__t_data = t_data
        # 임의의 W2, b2, W3, b3 준비
        self.__W2 = np.random.rand(2, 6)
        self.__b2 = np.random.rand(6)
        self.__W3 = np.random.rand(6, 1)
        self.__b3 = np.random.rand(1)
        self.__learning_rate = 1e-1
        self.loss_func = self.__feed_forward
    
    # feed_forward 함수로, 에러를 찾아줌
    def __feed_forward(self):
        delta = 1e-7
        # 입력층 -> 은닉층
        z2 = np.dot(self.__x_data, self.__W2) + self.__b2
        a2 = sigmoid(z2)
        # 은닉층 -> 출력층
        z3 = np.dot(a2, self.__W3) + self.__b3
        y = sigmoid(z3)
        # 크로스 엔트로피로 에러를 측정
        return -np.sum(self.__t_data * np.log(y + delta) + (1 - self.__t_data) * np.log(1 - y + delta))
    
    def train(self):
        f = lambda x: self.__feed_forward()
        print("Initial W2 = ", self.__W2, "b2 = ", self.__b2, "W3 = ", self.__W3, "b3 = ", self.__b3, "error_val = ", self.loss_func())
        for step in range(8001):
            self.__W2 -= self.__learning_rate * numerical_derivative(f, self.__W2)
            self.__b2 -= self.__learning_rate * numerical_derivative(f, self.__b2)
            self.__W3 -= self.__learning_rate * numerical_derivative(f, self.__W3)
            self.__b3 -= self.__learning_rate * numerical_derivative(f, self.__b3)
            if step % 400 == 0:
                print("step = ", step, "W2 = ", self.__W2, "b2 = ", self.__b2, "W3 = ", self.__W3, "b3 = ", self.__b3, "error_val = ", self.loss_func())
                
    def predict(self, x_data):
        z2 = np.dot(x_data, self.__W2) + self.__b2
        a2 = sigmoid(z2)
        z3 = np.dot(a2, self.__W3) + self.__b3
        pro = sigmoid(z3)
        if pro < 0.5:
            return 0, pro
        return 1, pro

# XOR 데이터
x_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]]).reshape([4, 2])
y_data = np.array([0, 1, 1, 0]).reshape([4, 1])

# 학습
XOR_Gate = LogicGate("XOR_Gate", x_data, y_data)
XOR_Gate.train()

# 출력
print(XOR_Gate.predict([0, 0]))
print(XOR_Gate.predict([1, 0]))
print(XOR_Gate.predict([0, 1]))
print(XOR_Gate.predict([1, 1]))

Initial W2 =  [[0.15497813 0.37606227 0.05464317 0.73416074 0.13254254 0.56784939]
 [0.97675137 0.29971758 0.22062862 0.77747002 0.31123737 0.25684498]] b2 =  [0.2515533  0.63807937 0.10719994 0.45994386 0.79376504 0.3674299 ] W3 =  [[0.54904977]
 [0.60140594]
 [0.62778196]
 [0.89200565]
 [0.94255703]
 [0.52393964]] b3 =  [0.49932258] error_val =  6.875613913762543
step =  0 W2 =  [[0.14683811 0.36666287 0.04040453 0.72536372 0.11716185 0.55907607]
 [0.96845546 0.29028819 0.20632401 0.76860408 0.29574055 0.24807265]] b2 =  [0.23074036 0.61597721 0.07843224 0.43131962 0.75938887 0.34685902] W3 =  [[0.42304779]
 [0.46813677]
 [0.52530096]
 [0.75421848]
 [0.80798704]
 [0.39849859]] b3 =  [0.32191781] error_val =  5.558590974623474
step =  400 W2 =  [[-0.04168447  0.33571296  0.00942622  1.89483371  0.12401488  0.54774569]
 [ 0.9934384   0.23623135  0.17111474  1.92089366  0.25690169  0.15024522]] b2 =  [0.19062897 0.57099887 0.01113855 0.17605374 0.66896169 0.29623519] W3 =  [[-0.43480466

In [20]:
# 패키지 임포트
import numpy as np

# 학습 데이터 셋 생성
X=np.array(
    [1,2,3,4,5]
).reshape(5,1)
X


y=np.array(
    [2,3,4,5,6]
).reshape(5,1)
y

# W,b 초기화
W=np.random.rand(1,1)
b=np.random.rand(1)
print(
    "W=",W,
    ",W.shape",W.shape,
    ",b=",b,
    ",b.shape",b.shape
)

# 손실함수 정의
def loss_func(x, t):
  # H(x)를 정의 - 행렬 계산
  y=np.dot(x,W)+b
  return np.sum((t - y)**2) /len(x)

# 수치미분 함수 정의
def numerical_derivative(fx, input_list):
  delta_x=1e-4 # 1* 0.00001
  ret=np.zeros_like(input_list)
  it=np.nditer(input_list, flags=['multi_index'], op_flags=['readwrite'])
  while not it.finished:
    i=it.multi_index
    tmp=input_list[i]
    input_list[i]=float(tmp) - delta_x
    f1=fx(input_list)
    input_list[i]=float(tmp) + delta_x
    f2=fx(input_list)
    ret[i]=(f2-f1) / (delta_x*2)
    input_list[i]=tmp
    it.iternext()
  return ret


# 손실함수 계산- 에러 값 계산
def error_val(x, t):
  # H(x)를 정의 - 행렬 계산
  y=np.dot(x,W)+b
  return np.sum((t - y)**2) /len(x)


# W,b 업데이트 수행 - 학습
#학습율
learning_rate=1e-2
f = lambda x: loss_func(X, y)
print(
    "초기 에러 값 =", error_val(X,y),
    "초기 W 값 =",W,
    "초기 b 값 =",b
)
for step in range(10001):
  # W,b 를 경사하강으로 업데이트
  W -= numerical_derivative(f,W) * learning_rate
  b -= numerical_derivative(f,b) * learning_rate
  if step % 500 == 0:
    print(
        "step = ", step,
        "에러 값 =", error_val(X,y),
        "W 값 =",W,
        "b 값 =",b
    )


# 학습된 결과로 현장 적용 후 예측 함수 정의
def predict(x):
  y=np.dot(x,W)+b
  return y

predict(47)

W= [[0.42894247]] ,W.shape (1, 1) ,b= [0.43410131] ,b.shape (1,)
초기 에러 값 = 5.846379299875832 초기 W 값 = [[0.42894247]] 초기 b 값 = [0.43410131]
step =  0 에러 값 = 3.4513899309077245 W 값 = [[0.58852905]] b 값 = [0.47010754]
step =  500 에러 값 = 0.0010104699239588577 W 값 = [[1.02064232]] b 값 = [0.92549293]
step =  1000 에러 값 = 3.2404068532644366e-05 W 값 = [[1.00369655]] b 값 = [0.98665755]
step =  1500 에러 값 = 1.039143899853774e-06 W 값 = [[1.00066196]] b 값 = [0.99761068]
step =  2000 에러 값 = 3.3323594644125554e-08 W 값 = [[1.00011854]] b 값 = [0.99957213]
step =  2500 에러 값 = 1.068631553483198e-09 W 값 = [[1.00002123]] b 값 = [0.99992338]
step =  3000 에러 값 = 3.426921403000274e-11 W 값 = [[1.0000038]] b 값 = [0.99998628]
step =  3500 에러 값 = 1.0989559740584496e-12 W 값 = [[1.00000068]] b 값 = [0.99999754]
step =  4000 에러 값 = 3.524166709683615e-14 W 값 = [[1.00000012]] b 값 = [0.99999956]
step =  4500 에러 값 = 1.130140917962247e-15 W 값 = [[1.00000002]] b 값 = [0.99999992]
step =  5000 에러 값 = 3.6241713809220476e-17 W 값

array([[48.]])

# deep learning

## 텐서플로  익히기

In [21]:
import tensorflow as tf
with tf.compat.v1.Session() as sess:
   helloworld = tf.constant("Hello World!")
   print(sess.run(helloworld))

b'Hello World!'


# 딥러닝

In [22]:
import tensorflow as tf

In [23]:
tf.__version__

'2.13.0'

In [24]:
# 텐서 생성
x=tf.constant(3)
y=x**2

# 세션 객체 생성
# sess=tf.Session()

# 세션 객체를 이용해서 텐서를 사용
# print(sess.run(x))
# print(sess.run(y))

# sess.close()
# sess.close()

tf.print(x)
tf.print(y)


3
9


### 텐서

In [25]:
import tensorflow as tf

print(tf.__version__)
a=tf.random.uniform([2,3],0,1)
print(a)
print(type(a))

2.13.0
tf.Tensor(
[[0.10273719 0.4762597  0.23663199]
 [0.30076706 0.73779476 0.17305231]], shape=(2, 3), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [26]:
import tensorflow as tf
import numpy as np

t=tf.random.uniform([2,3],0,1)
n=np.random.uniform(0,1,[2,3])
print("tensorflow로 생성한 텐서:\n",t,"\n")
print("numpy로 생성한 ndarray:\n",n,"\n")

res=t+n # 텐서 t와 ndarray n의 덧셈
print("덧셈 결과:\n",res)

tensorflow로 생성한 텐서:
 tf.Tensor(
[[0.8067726  0.86146724 0.80488276]
 [0.00330651 0.27930796 0.48967326]], shape=(2, 3), dtype=float32) 

numpy로 생성한 ndarray:
 [[0.04154067 0.72644253 0.10191643]
 [0.83466477 0.70079021 0.61053252]] 

덧셈 결과:
 tf.Tensor(
[[0.8483133  1.5879097  0.9067992 ]
 [0.83797127 0.9800982  1.1002058 ]], shape=(2, 3), dtype=float32)


## 텐서 기본 사용

In [27]:
#import tensorflow as tf

import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

x = tf.placeholder(tf.float32, shape=[None])
y = tf.placeholder(tf.float32, shape=[None])

W = tf.Variable(tf.random_normal([1]), name="weight")
b = tf.Variable(tf.random_normal([1]), name="bias")

hypothesis = x * W + b
cost = tf.reduce_mean(tf.square(hypothesis - y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    _cost, _W, _b, _ = \
        sess.run([cost, W, b, train],
            feed_dict={x: [1, 2, 3, 4, 5], y: [2.1, 3.1, 4.1, 5.1, 6.1]})
    if step % 20 == 0:
        print(step, _cost, _W, _b)

print(sess.run(hypothesis, feed_dict={x: [5]}))
print(sess.run(hypothesis, feed_dict={x: [2.5]}))
print(sess.run(hypothesis, feed_dict={x: [1.5, 3.5]}))

Instructions for updating:
non-resource variables are not supported in the long term
0 0.9993008 [0.78949046] [1.0288727]
20 4.306994e-05 [1.0021161] [1.0886061]
40 1.9811618e-05 [1.0028756] [1.089601]
60 1.7304252e-05 [1.0026914] [1.0902828]
80 1.511044e-05 [1.0025152] [1.0909193]
100 1.3196812e-05 [1.0023504] [1.091514]
120 1.1524165e-05 [1.0021966] [1.0920697]
140 1.0064541e-05 [1.0020528] [1.092589]
160 8.789874e-06 [1.0019182] [1.0930742]
180 7.676485e-06 [1.0017927] [1.0935277]
200 6.7038854e-06 [1.0016752] [1.0939516]
220 5.8540836e-06 [1.0015656] [1.0943477]
240 5.1129327e-06 [1.001463] [1.0947177]
260 4.4653216e-06 [1.0013673] [1.0950634]
280 3.900122e-06 [1.0012778] [1.0953867]
300 3.4061547e-06 [1.0011942] [1.0956887]
320 2.9746375e-06 [1.001116] [1.095971]
340 2.5974934e-06 [1.0010428] [1.0962348]
360 2.2691063e-06 [1.0009745] [1.0964812]
380 1.9816384e-06 [1.0009109] [1.0967118]
400 1.7305067e-06 [1.0008513] [1.0969269]
420 1.5113512e-06 [1.0007955] [1.0971282]
440 1.32003

In [28]:
#import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
#데이터 셋
x_train=[1,2,3]
y_train=[4,5,6]
W=tf.Variable(tf.random_normal([1]), name="weight")
b=tf.Variable(tf.random_normal([1]), name="bias")
#(H(x))
hypothesis=x_train*W+b
#손실함수
cost=tf.reduce_mean(tf.square(hypothesis-y_train))
#경사하강
optimizer=tf.train.GradientDescentOptimizer(learning_rate=0.01)
#개선
train=optimizer.minimize(cost)
#훈련
sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
    sess.run(train)
    if (step % 20 == 0):
        print(step, '\t', sess.run(cost), '\t', sess.run(W), '\t', sess.run(b))


0 	 43.741093 	 [-0.71942544] 	 [-0.02413182]
20 	 0.86226827 	 [1.5532498] 	 [1.082198]
40 	 0.4307567 	 [1.7359571] 	 [1.2641386]
60 	 0.3880254 	 [1.721243] 	 [1.3544599]
80 	 0.3523816 	 [1.6892394] 	 [1.4326268]
100 	 0.3200384 	 [1.657028] 	 [1.5063668]
120 	 0.29066414 	 [1.6261673] 	 [1.5765694]
140 	 0.26398587 	 [1.5967414] 	 [1.6434659]
160 	 0.23975621 	 [1.568697] 	 [1.7072182]
180 	 0.21775042 	 [1.5419703] 	 [1.7679743]
200 	 0.1977644 	 [1.5164995] 	 [1.8258749]
220 	 0.1796128 	 [1.4922261] 	 [1.8810545]
240 	 0.1631272 	 [1.4690933] 	 [1.933641]
260 	 0.14815465 	 [1.4470476] 	 [1.983756]
280 	 0.13455655 	 [1.426038] 	 [2.0315156]
300 	 0.12220632 	 [1.4060156] 	 [2.0770311]
320 	 0.11098962 	 [1.3869343] 	 [2.1204076]
340 	 0.10080254 	 [1.3687497] 	 [2.1617455]
360 	 0.09155041 	 [1.3514197] 	 [2.2011406]
380 	 0.08314758 	 [1.3349042] 	 [2.2386837]
400 	 0.07551593 	 [1.319165] 	 [2.274463]
420 	 0.0685849 	 [1.3041656] 	 [2.30856]
440 	 0.062289882 	 [1.289871] 	

In [29]:
#import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
#데이터 셋
x_train=tf.placeholder(tf.float32, shape=[None]) #x_train=[1,2,3]
y_train=tf.placeholder(tf.float32, shape=[None]) #y_train=[1,2,3]
W=tf.Variable(tf.random_normal([1]), name="weight")
b=tf.Variable(tf.random_normal([1]), name="bias")
#(H(x))
hypothesis=x_train*W+b
#손실함수
cost=tf.reduce_mean(tf.square(hypothesis-y_train))
#경사하강
optimizer=tf.train.GradientDescentOptimizer(learning_rate=0.01)
#개선
train=optimizer.minimize(cost)
#훈련
sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
    #sess.run(train)
    _cost, _W, _b, _= \
      sess.run([cost, W, b, train],
               feed_dict={
                   x_train: [1,2,3],
                   y_train: [4,5,6]
               })
    if step % 20 == 0:
      print(step, _cost, _W, _b)
print(sess.run(hypothesis, feed_dict={x_train: [4]}))

0 99.783165 [-1.5646023] [-0.5082631]
20 1.4201412 [1.5082887] [0.9553625]
40 0.48100233 [1.7655232] [1.1751189]
60 0.429521 [1.7563148] [1.2726569]
80 0.39003155 [1.7233198] [1.3549567]
100 0.35423222 [1.689569] [1.4323745]
120 0.32171935 [1.6571848] [1.5060574]
140 0.29219082 [1.6263018] [1.576268]
160 0.26537216 [1.5968682] [1.6431783]
180 0.24101532 [1.5688175] [1.7069439]
200 0.21889405 [1.5420852] [1.7677128]
220 0.1988029 [1.5166091] [1.825626]
240 0.18055601 [1.4923304] [1.8808172]
260 0.16398396 [1.469193] [1.9334146]
280 0.14893274 [1.4471425] [1.98354]
300 0.13526316 [1.4261285] [2.0313098]
320 0.122848146 [1.4061018] [2.0768352]
340 0.11157262 [1.3870165] [2.1202207]
360 0.10133187 [1.3688279] [2.1615674]
380 0.09203116 [1.3514942] [2.2009711]
400 0.08358409 [1.3349752] [2.2385225]
420 0.07591249 [1.3192327] [2.274309]
440 0.06894489 [1.30423] [2.3084142]
460 0.06261689 [1.2899321] [2.3409162]
480 0.056869607 [1.2763064] [2.3718905]
500 0.051649958 [1.2633212] [2.4014094]
5

## XOR 문제 해결을

In [32]:
#import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

import numpy as np

xy = np.loadtxt('./datasets/train.txt')
print(xy)

[[0. 0. 0.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 0.]]


In [33]:
x_data = xy[0:-1]
y_data = xy[-1]

print(x_data)
print("*****")
print(y_data)

[[0. 0. 0.]
 [0. 1. 1.]
 [1. 0. 1.]]
*****
[1. 1. 0.]


In [34]:
X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

W = tf.Variable(tf.random_uniform([1, len(x_data)], -1.0, 1.0))

In [35]:
# Our hypothesis
h = tf.matmul(W, X)
hypothesis = tf.div(1., 1.+tf.exp(-h))

# Cross entropy cost function
cost = -tf.reduce_mean(Y*tf.log(hypothesis) + (1-Y)*tf.log(1-hypothesis))

learning_rate = tf.Variable(0.01)
optimizer = tf.train.GradientDescentOptimizer(learning_rate)
train = optimizer.minimize(cost)


init = tf.global_variables_initializer()

Instructions for updating:
Deprecated in favor of operator or tf.math.divide.


In [36]:
with tf.Session() as sess:
    sess.run(init)
    for step in range(5001):
        sess.run(train, feed_dict={X:x_data, Y:y_data })
        if step % 500 == 0:
            print(step, sess.run(cost, feed_dict={X:x_data, Y:y_data}), sess.run(W))

# Test model
    correct_prediction = tf.equal(tf.floor(hypothesis+0.5), Y)

# Calculate Accuracy
    accuracy = tf.reduce_mean(tf.cast(correct_prediction, "float"))
    print(sess.run([hypothesis, tf.floor(hypothesis+0.5), correct_prediction, accuracy],feed_dict={X:x_data, Y:y_data}))
    print("Accuracy:", accuracy.eval({X:x_data, Y:y_data}))

0 0.7252005 [[ 0.71703076  0.7086452  -0.23521915]]
500 0.7024825 [[ 0.71703076  0.3825419  -0.24412015]]
1000 0.696812 [[ 0.71703076  0.22698489 -0.1870924 ]]
1500 0.69470924 [[ 0.71703076  0.14232782 -0.13088115]]
2000 0.6938238 [[ 0.71703076  0.09171871 -0.08843996]]
2500 0.6934411 [[ 0.71703076  0.05985419 -0.05891579]]
3000 0.6932748 [[ 0.71703076  0.03927973 -0.03901122]]
3500 0.6932027 [[ 0.71703076  0.02584113 -0.02576433]]
4000 0.69317126 [[ 0.71703076  0.01701849 -0.01699655]]
4500 0.6931577 [[ 0.71703076  0.0112133  -0.01120706]]
5000 0.69315165 [[ 0.71703076  0.00738981 -0.00738807]]
[array([[0.49815303, 0.50184745, 0.5000004 ]], dtype=float32), array([[0., 1., 1.]], dtype=float32), array([[False,  True, False]]), 0.33333334]
Accuracy: 0.33333334


# 신경망 구현: MLP: Neural Network with 2 layers

In [38]:
#import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import numpy as np
xy = np.loadtxt('./datasets/train.txt', unpack=True)
x_data = np.transpose(xy[0:-1])
y_data = np.reshape(xy[-1],(4,1))
X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)
# define 2 layer Neural Network
W1 = tf.Variable(tf.random_uniform([2, 2], -1.0, 1.0))
W2 = tf.Variable(tf.random_uniform([2, 1], -1.0, 1.0))
b1 = tf.Variable(tf.zeros([2]), name="Bias1")
b2 = tf.Variable(tf.zeros([1]), name="Bias2")
# Our hypothesis
L2 = tf.sigmoid(tf.matmul(X, W1)+b1)
hypothesis = tf.sigmoid(tf.matmul(L2, W2)+b2)
# Cross entropy cost function
cost = -tf.reduce_mean(Y*tf.log(hypothesis) + (1-Y)*tf.log(1-hypothesis))
# For this time, learning rate is very important.
learning_rate = tf.Variable(0.1)
optimizer = tf.train.GradientDescentOptimizer(learning_rate)
train = optimizer.minimize(cost)
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    for step in range(7001):
        sess.run(train, feed_dict={X:x_data, Y:y_data})
        if step % 500 == 0:
            print(step, sess.run(cost, feed_dict={X:x_data, Y:y_data}))
    # Test model
    correct = tf.equal(tf.floor(hypothesis+0.5), Y)
    # Calculate Accuracy
    accuracy = tf.reduce_mean(tf.cast(correct, "float"))
    print(sess.run([hypothesis],feed_dict={X:x_data, Y:y_data}))
    print("Accuracy:", accuracy.eval({X:x_data, Y:y_data}))

0 0.6944671
500 0.68914855
1000 0.6775025
1500 0.6406398
2000 0.5671855
2500 0.49148384
3000 0.4401438
3500 0.41030782
4000 0.3929873
4500 0.38231283
5000 0.3752889
5500 0.37039945
6000 0.3668368
6500 0.36414373
7000 0.36204618
[array([[0.01493686],
       [0.9786948 ],
       [0.4969698 ],
       [0.5095214 ]], dtype=float32)]
Accuracy: 0.5


# 신경망 구현: MLP: Wide Neural Network with 2 layers

In [39]:
#import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import numpy as np
xy = np.loadtxt('./datasets/train.txt', unpack=True)
x_data = np.transpose(xy[0:-1])
y_data = np.reshape(xy[-1],(4,1))
X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)
# define 2 layer Neural Network - we will use 10 units
W1 = tf.Variable(tf.random_uniform([2, 10], -1.0, 1.0))
W2 = tf.Variable(tf.random_uniform([10, 1], -1.0, 1.0))
b1 = tf.Variable(tf.zeros([10]), name="Bias1")
b2 = tf.Variable(tf.zeros([1]), name="Bias2")
# Our hypothesis
L2 = tf.sigmoid(tf.matmul(X, W1)+b1)
hypothesis = tf.sigmoid(tf.matmul(L2, W2)+b2)
# Cross entropy cost function
cost = -tf.reduce_mean(Y*tf.log(hypothesis) + (1-Y)*tf.log(1-hypothesis))
# For this time, learning rate is very important.
learning_rate = tf.Variable(0.1)
optimizer = tf.train.GradientDescentOptimizer(learning_rate)
train = optimizer.minimize(cost)
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    for step in range(30001):
        sess.run(train, feed_dict={X:x_data, Y:y_data})
        if step % 2000 == 0:
            print(step, sess.run(cost, feed_dict={X:x_data, Y:y_data}))
    # Test model
    correct = tf.equal(tf.floor(hypothesis+0.5), Y)
    # Calculate Accuracy
    accuracy = tf.reduce_mean(tf.cast(correct, "float"))
    print(sess.run([hypothesis],feed_dict={X:x_data, Y:y_data}))
    print("Accuracy:", accuracy.eval({X:x_data, Y:y_data}))

0 0.7452563
2000 0.52043855
4000 0.0638545
6000 0.022211395
8000 0.012534449
10000 0.0085215345
12000 0.0063795215
14000 0.0050636344
16000 0.0041796113
18000 0.0035477756
20000 0.0030752304
22000 0.002709373
24000 0.002418228
26000 0.0021814043
28000 0.0019852077
30000 0.0018200991
[array([[7.4531906e-04],
       [9.9822938e-01],
       [9.9802375e-01],
       [2.7805574e-03]], dtype=float32)]
Accuracy: 1.0


# 신경망 구현: MLP: Deep Neural Network

In [40]:
#import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import numpy as np
xy = np.loadtxt('./datasets/train.txt', unpack=True)
x_data = np.transpose(xy[0:-1])
y_data = np.reshape(xy[-1],(4,1))
X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)
# define 2 layer Neural Network - we will use 3 layers.
W1 = tf.Variable(tf.random_uniform([2,10], -1.0, 1.0))
W2 = tf.Variable(tf.random_uniform([10,5], -1.0, 1.0))
W3 = tf.Variable(tf.random_uniform([5,1], -1.0, 1.0))
b1 = tf.Variable(tf.zeros([10]), name="Bias1")
b2 = tf.Variable(tf.zeros([5]), name="Bias2")
b3 = tf.Variable(tf.zeros([1]), name="Bias3")
# Our hypothesis
L2 = tf.sigmoid(tf.matmul(X, W1) + b1)
L3 = tf.sigmoid(tf.matmul(L2, W2) + b2)
hypothesis = tf.sigmoid(tf.matmul(L3, W3) + b3)
# Cross entropy cost function
cost = -tf.reduce_mean(Y*tf.log(hypothesis) + (1-Y)*tf.log(1-hypothesis))
# For this time, learning rate is very important.
learning_rate = tf.Variable(0.1)
optimizer = tf.train.GradientDescentOptimizer(learning_rate)
train = optimizer.minimize(cost)
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    for step in range(30001):
        sess.run(train, feed_dict={X:x_data, Y:y_data})
        if step % 2000 == 0:
            print(step,
                sess.run(cost, feed_dict={X:x_data, Y:y_data})
                #sess.run(W1),
                #sess.run(W2)
            )
    # Test model
    correct = tf.equal(tf.floor(hypothesis+0.5), Y)
    accuracy = tf.reduce_mean(tf.cast(correct, "float"))
    print(sess.run([hypothesis],feed_dict={X:x_data, Y:y_data}))
    print("Accuracy:", accuracy.eval({X:x_data, Y:y_data}))


0 0.7095448
2000 0.60121936
4000 0.040793866
6000 0.0086068995
8000 0.0043414305
10000 0.0028203991
12000 0.0020622173
14000 0.001614095
16000 0.001320327
18000 0.0011138516
20000 0.0009613152
22000 0.0008442559
24000 0.0007517586
26000 0.0006769562
28000 0.0006152518
30000 0.00056351157
[array([[2.7359382e-04],
       [9.9937958e-01],
       [9.9934131e-01],
       [7.0066575e-04]], dtype=float32)]
Accuracy: 1.0


In [41]:
# 신경망 구현: MLP: Deep Neural Network 좀 더 깊이를 더하면…

In [42]:
#import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import numpy as np
xy = np.loadtxt('./datasets/train.txt', unpack=True)
x_data = np.transpose(xy[0:-1])
y_data = np.reshape(xy[-1],(4,1))
X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)
# define 2 layer Neural Network - we will use 3 layers.
W1 = tf.Variable(tf.random_uniform([2,10], -1.0, 1.0))
W2 = tf.Variable(tf.random_uniform([10,10], -1.0, 1.0))
W3 = tf.Variable(tf.random_uniform([10,10], -1.0, 1.0))
W4 = tf.Variable(tf.random_uniform([10,1], -1.0, 1.0))
b1 = tf.Variable(tf.zeros([10]), name="Bias1")
b2 = tf.Variable(tf.zeros([10]), name="Bias2")
b3 = tf.Variable(tf.zeros([10]), name="Bias3")
b4 = tf.Variable(tf.zeros([1]), name="Bias4")
# Our hypothesis
L2 = tf.sigmoid(tf.matmul(X, W1) + b1)
L3 = tf.sigmoid(tf.matmul(L2, W2) + b2)
L4 = tf.sigmoid(tf.matmul(L3, W3) + b2)
hypothesis = tf.sigmoid(tf.matmul(L4, W4) + b4)
# Cross entropy cost function
cost = -tf.reduce_mean(Y*tf.log(hypothesis) + (1-Y)*tf.log(1-hypothesis))
# For this time, learning rate is very important.
learning_rate = tf.Variable(0.3)
optimizer = tf.train.GradientDescentOptimizer(learning_rate)
train = optimizer.minimize(cost)
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    for step in range(30001):
        sess.run(train, feed_dict={X:x_data, Y:y_data})
        if step % 2000 == 0:
            print(step,
                sess.run(cost, feed_dict={X:x_data, Y:y_data})
                #sess.run(W1),
                #sess.run(W2)
            )
    # Test model
    correct = tf.equal(tf.floor(hypothesis+0.5), Y)
    accuracy = tf.reduce_mean(tf.cast(correct, "float"))
    print(sess.run([hypothesis],feed_dict={X:x_data, Y:y_data}))
    print("Accuracy:", accuracy.eval({X:x_data, Y:y_data}))


0 0.7009176
2000 0.6793457
4000 0.0026507694
6000 0.0009860427
8000 0.00058764446
10000 0.00041332858
12000 0.00031661283
14000 0.00025546993
16000 0.00021349794
18000 0.00018300382
20000 0.00015985817
22000 0.00014173548
24000 0.00012716008
26000 0.00011523765
28000 0.00010528252
30000 9.6862466e-05
[array([[6.20432766e-05],
       [9.99892473e-01],
       [9.99902010e-01],
       [1.19836724e-04]], dtype=float32)]
Accuracy: 1.0


# 텐서플로와 케라스

학습 시간이 많이 걸립니다. 시간이 많을 때 실행 해 보세요 ^^

In [ ]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

# 3.27 tf.keras 를 이용한 XOR 네트워크 계산
import numpy as np
x = np.array([[1,1], [1,0], [0,1], [0,0]])
y = np.array([[0], [1], [1], [0]])
model = tf.keras.Sequential([
    tf.keras.layers.Dense(units=2, activation='sigmoid', input_shape=(2,)),
    tf.keras.layers.Dense(units=1, activation='sigmoid')
])
model.compile(optimizer=tf.keras.optimizers.SGD(lr=0.3), loss='mse')
model.summary()


# 3.28 tf.keras 를 이용한 XOR 네트워크 학습
history = model.fit(x, y, epochs=2000, batch_size=1)

# 3.29 tf.keras 를 이용한 XOR 네트워크 평가
model.predict(x)

# 3.30 XOR 네트워크의 가중치와 편향 확인
for weight in model.weights:
    print(weight)

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Train on 4 samples


C:\DEV\miniconda3\envs\tf38_cpu\lib\site-packages\keras\src\optimizers\legacy\gradient_descent.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


Epoch 1/2000
4/4 [==============================] - 0s 3ms/sample - loss: 0.2756
Epoch 2/2000
4/4 [==============================] - 0s 3ms/sample - loss: 0.2752
Epoch 3/2000
4/4 [==============================] - 0s 2ms/sample - loss: 0.2748
Epoch 4/2000
4/4 [==============================] - 0s 8ms/sample - loss: 0.2756
Epoch 5/2000
4/4 [==============================] - 0s 11ms/sample - loss: 0.2730
Epoch 6/2000
4/4 [==============================] - 0s 5ms/sample - loss: 0.2737
Epoch 7/2000
4/4 [==============================] - 0s 6ms/sample - loss: 0.2727
Epoch 8/2000
4/4 [==============================] - 0s 3ms/sample - loss: 0.2730
Epoch 9/2000
4/4 [==============================] - 0s 4ms/sample - loss: 0.2728
Epoch 10/2000
4/4 [==============================] - 0s 4ms/sample - loss: 0.2727
Epoch 11/2000
4/4 [==============================] - 0s 2ms/sample - loss: 0.2725
Epoch 12/2000
4/4 [==============================] - 0s 32ms/sample - loss: 0.2726
Epoch 13/2000
4/4 [====

In [59]:
import numpy as np

print(np.__version__)

1.24.3


In [62]:
pip install numpy==1.24.3

  Using cached numpy-1.24.3-cp38-cp38-win_amd64.whl.metadata (5.6 kB)
Using cached numpy-1.24.3-cp38-cp38-win_amd64.whl (14.9 MB)
  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.5
    Uninstalling numpy-1.19.5:
      Successfully uninstalled numpy-1.19.5
Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [95]:
import tensorflow as tf

# Enable eager execution
tf.compat.v1.disable_v2_behavior()
# Eager execution must be called at the beginning of the program
tf.compat.v1.enable_eager_execution()

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD
import numpy as np

# OR 데이터 구축
x = np.array([[0.0, 0.0], [0.0, 1.0], [1.0, 0.0], [1.0, 1.0]])
y = np.array([[-1], [1], [1], [1]])

# Define the model
perceptron = Sequential([
    Dense(units=1, activation='tanh', input_shape=(2,))
])

# Compile the model
perceptron.compile(loss='mse', optimizer=SGD(learning_rate=0.1), metrics=['mse'])

# Train the model
perceptron.fit(x, y, epochs=500, verbose=2)

# Predict using the trained model
res = perceptron.predict(x)
print(res)


ValueError: tf.enable_eager_execution must be called at program startup.

# LeNet-5 사례 [LeCun1998] 재현해 보기

In [66]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D,MaxPooling2D,Flatten,Dense
from tensorflow.keras.optimizers import Adam

# MNIST 데이터셋을 읽고 신경망에 입력할 형태로 변환
(x_train,y_train),(x_test,y_test)= mnist.load_data()
x_train=x_train.reshape(60000,28,28,1)
x_test=x_test.reshape(10000,28,28,1)
x_train=x_train.astype(np.float32)/255.0
x_test=x_test.astype(np.float32)/255.0
y_train=tf.keras.utils.to_categorical(y_train,10)
y_test=tf.keras.utils.to_categorical(y_test,10)

# LeNet-5 신경망 모델 설계
cnn=Sequential()
cnn.add(Conv2D(6,(5,5),padding='same',activation='relu',input_shape=(28,28,1)))
cnn.add(MaxPooling2D(pool_size=(2,2)))
cnn.add(Conv2D(16,(5,5),padding='same',activation='relu'))
cnn.add(MaxPooling2D(pool_size=(2,2)))
cnn.add(Conv2D(120,(5,5),padding='same',activation='relu'))
cnn.add(Flatten())
cnn.add(Dense(84,activation='relu'))
cnn.add(Dense(10,activation='softmax'))

# 신경망 모델 학습
cnn.compile(loss='categorical_crossentropy',optimizer=Adam(),metrics=['accuracy'])
hist=cnn.fit(x_train,y_train,batch_size=128,epochs=30,validation_data=(x_test,y_test),verbose=2)

# 신경망 모델 정확률 평가
res=cnn.evaluate(x_test,y_test,verbose=0)
print("정확률은",res[1]*100)

NotImplementedError: numpy() is only available when eager execution is enabled.

In [67]:
import matplotlib.pyplot as plt

# 정확률 그래프
plt.plot(hist.history['accuracy'])
plt.plot(hist.history['val_accuracy'])
plt.title('Model accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(['Train','Validation'],loc='best')
plt.grid()
plt.show()

# 손실 함수 그래프
plt.plot(hist.history['loss'])
plt.plot(hist.history['val_loss'])
plt.title('Model loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend(['Train','Validation'],loc='best')
plt.grid()
plt.show()

NameError: name 'hist' is not defined

# RNN

In [78]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import numpy as np

tf.compat.v1.set_random_seed(777)  # reproducibility

idx2char = ['h', 'i', 'e', 'l', 'o']
# Teach hello: hihell -> ihello
x_data = [[0, 1, 0, 2, 3, 3]]   # hihell
x_one_hot = np.array([[[1, 0, 0, 0, 0],   # h 0
                       [0, 1, 0, 0, 0],   # i 1
                       [1, 0, 0, 0, 0],   # h 0
                       [0, 0, 1, 0, 0],   # e 2
                       [0, 0, 0, 1, 0],   # l 3
                       [0, 0, 0, 1, 0]]])  # l 3

y_data = [[1, 0, 2, 3, 3, 4]]    # ihello

num_classes = 5
input_dim = 5  # one-hot size
hidden_size = 5  # output from the LSTM. 5 to directly predict one-hot
batch_size = 1   # one sentence
sequence_length = 6  # |ihello| == 6
learning_rate = 0.1

X = tf.placeholder(
    tf.float32, [None, sequence_length, input_dim])  # X one-hot
Y = tf.placeholder(tf.int32, [None, sequence_length])  # Y label

# Define LSTM cell
cell = tf.compat.v1.nn.rnn_cell.BasicLSTMCell(num_units=hidden_size, state_is_tuple=True, reuse=tf.compat.v1.AUTO_REUSE)

# Initialize cell state
initial_state = cell.zero_state(batch_size, tf.float32)

# Run dynamic RNN
outputs, _states = tf.compat.v1.nn.dynamic_rnn(
    cell, X, initial_state=initial_state, dtype=tf.float32)

# FC layer
X_for_fc = tf.reshape(outputs, [-1, hidden_size])
dense = tf.keras.layers.Dense(num_classes, activation=None)
outputs = dense(X_for_fc)

# Reshape output for sequence_loss
outputs = tf.reshape(outputs, [batch_size, sequence_length, num_classes])

weights = tf.ones([batch_size, sequence_length])
sequence_loss = tf.keras.losses.sparse_categorical_crossentropy(
    y_true=Y, y_pred=outputs, from_logits=True)
loss = tf.reduce_mean(sequence_loss)
train = tf.compat.v1.train.AdamOptimizer(learning_rate=learning_rate).minimize(loss)

prediction = tf.argmax(outputs, axis=2)

with tf.compat.v1.Session() as sess:
    sess.run(tf.compat.v1.global_variables_initializer())
    for i in range(50):
        l, _ = sess.run([loss, train], feed_dict={X: x_one_hot, Y: y_data})
        result = sess.run(prediction, feed_dict={X: x_one_hot})
        print(i, "loss:", l, "prediction: ", result, "true Y: ", y_data)

        # print char using dic
        result_str = [idx2char[c] for c in np.squeeze(result)]
        print("\tPrediction str: ", ''.join(result_str))


C:\Users\k8s\AppData\Local\Temp\ipykernel_9140\4088922680.py:31: UserWarning: `tf.nn.rnn_cell.BasicLSTMCell` is deprecated and will be removed in a future version. This class is equivalent as `tf.keras.layers.LSTMCell`, and will be replaced by that in Tensorflow 2.0.
  cell = tf.compat.v1.nn.rnn_cell.BasicLSTMCell(num_units=hidden_size, state_is_tuple=True, reuse=tf.compat.v1.AUTO_REUSE)


0 loss: 1.6231875 prediction:  [[3 3 3 3 3 3]] true Y:  [[1, 0, 2, 3, 3, 4]]
	Prediction str:  llllll
1 loss: 1.472727 prediction:  [[3 3 3 3 3 3]] true Y:  [[1, 0, 2, 3, 3, 4]]
	Prediction str:  llllll
2 loss: 1.3953539 prediction:  [[3 3 3 3 3 3]] true Y:  [[1, 0, 2, 3, 3, 4]]
	Prediction str:  llllll
3 loss: 1.3403486 prediction:  [[3 3 3 3 3 3]] true Y:  [[1, 0, 2, 3, 3, 4]]
	Prediction str:  llllll
4 loss: 1.2473465 prediction:  [[3 3 3 3 3 3]] true Y:  [[1, 0, 2, 3, 3, 4]]
	Prediction str:  llllll
5 loss: 1.1330713 prediction:  [[2 0 2 3 3 4]] true Y:  [[1, 0, 2, 3, 3, 4]]
	Prediction str:  ehello
6 loss: 1.0304064 prediction:  [[2 0 2 3 4 4]] true Y:  [[1, 0, 2, 3, 3, 4]]
	Prediction str:  eheloo
7 loss: 0.9380675 prediction:  [[0 0 2 3 4 4]] true Y:  [[1, 0, 2, 3, 3, 4]]
	Prediction str:  hheloo
8 loss: 0.8421379 prediction:  [[0 0 2 3 3 4]] true Y:  [[1, 0, 2, 3, 3, 4]]
	Prediction str:  hhello
9 loss: 0.7365717 prediction:  [[1 0 2 3 3 4]] true Y:  [[1, 0, 2, 3, 3, 4]]
	Predi

# LSTM

In [87]:
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)  # reproducibility

sample = "I am a boy. You're a girl."
idx2char = list(set(sample))  # index -> char
char2idx = {c: i for i, c in enumerate(idx2char)}  # char -> idex

# hyper parameters
dic_size = len(char2idx)  # RNN input size (one hot size)
hidden_size = len(char2idx)  # RNN output size
num_classes = len(char2idx)  # final output size (RNN or softmax, etc.)
batch_size = 1  # one sample data, one batch
sequence_length = len(sample) - 1  # number of lstm rollings (unit #)
learning_rate = 0.1

sample_idx = [char2idx[c] for c in sample]  # char to index
x_data = [sample_idx[:-1]]  # X data sample (0 ~ n-1) hello: hell
y_data = [sample_idx[1:]]   # Y label sample (1 ~ n) hello: ello

X = tf.placeholder(tf.int32, [None, sequence_length])  # X data
Y = tf.placeholder(tf.int32, [None, sequence_length])  # Y label

x_one_hot = tf.one_hot(X, num_classes)  # one hot: 1 -> 0 1 0 0 0 0 0 0 0 0
cell = tf.contrib.rnn.BasicLSTMCell(
    num_units=hidden_size, state_is_tuple=True)
initial_state = cell.zero_state(batch_size, tf.float32)

outputs, _states = tf.nn.dynamic_rnn(
    cell, x_one_hot, initial_state=initial_state, dtype=tf.float32)

# FC layer
X_for_fc = tf.reshape(outputs, [-1, hidden_size])
outputs = tf.contrib.layers.fully_connected(X_for_fc, num_classes, activation_fn=None)

# reshape out for sequence_loss
outputs = tf.reshape(outputs, [batch_size, sequence_length, num_classes])

weights = tf.ones([batch_size, sequence_length])
sequence_loss = tf.contrib.seq2seq.sequence_loss(
    logits=outputs, targets=Y, weights=weights)
loss = tf.reduce_mean(sequence_loss)
train = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(loss)

prediction = tf.argmax(outputs, axis=2)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for i in range(50):
        l, _ = sess.run([loss, train], feed_dict={X: x_data, Y: y_data})
        result = sess.run(prediction, feed_dict={X: x_data})

        # print char using dic
        result_str = [idx2char[c] for c in np.squeeze(result)]

        print(i, "loss:", l, "Prediction:", ''.join(result_str))


AttributeError: module 'tensorflow' has no attribute 'set_random_seed'